
GET http://localhost:5149


###
GET http://localhost:5149/api/categories
Content-Type: application/json
# GET http://localhost:5149/api/categories?searchValue=Laptop

###
GET http://localhost:5149/api/categories/fd127c3b-d30d-4fd1-b409-9ddf42e4eab9
Content-Type: application/json


###
POST http://localhost:5149/api/categories/
Content-Type: application/json

//top-button-space rakhte hbe---------!
{
"name":"Laptop",
"description":"my good laptop.!"
}


###
PUT http://localhost:5149/api/categories/fd127c3b-d30d-4fd1-b409-9ddf42e4eab9
Content-Type: application/json

{
"name":"Nokia",
"description":"Good Phone is Nokia..!"
}

###
DELETE http://localhost:5149/api/categories/fd127c3b-d30d-4fd1-b409-9ddf42e4eab9

Content-Type: application/json