
GET http://localhost:5149


###
GET http://localhost:5149/api/categories
# GET http://localhost:5149/api/categories?searchValue=Laptop

###
GET http://localhost:5149/api/categories/49fdbccd-48f4-40c6-9bd5-6b6fd1d40bae


###
POST http://localhost:5149/api/categories/
Content-Type: application/json

//top-button-space rakhte hbe---------!
{
    "name":"K ewyewrv",
    "description":""
}


###
PUT http://localhost:5149/api/categories/9a3c7c2e-f29e-4ad9-83e2-c10910d50ea1
Content-Type: application/json

{
    "name":"Nokia",
    "description":"Good Phone is Nokia..!"
}

###
DELETE http://localhost:5149/api/categories/9a3c7c2e-f29e-4ad9-83e2-c10910d50ea1